xbtn = '//button[@class="mat_close"]'

class com:
    """COMMON"""
    proceedToPayBtn = '//button[text()="Proceed to Pay"]'
    cancelPaymentBtn = '//button[text()="Cancel Payment"]'
    
    payerAuthenticationFrame = '//iframe[@title="Payer Authentication"]|//iframe[@title="Bank Authentication"]'
    enterCodeHereTxt = '//input[@placeholder=" Enter Code Here"]'
    #passwordTxt = '//input[@type="password"]'
    paymentSecurityForm = '//section[@id="content"]'
    continueBtn = '//input[@value="CONTINUE"]'
    submitBtn = '//input[@value="SUBMIT"] | //input[@type="submit"][@value="Submit"]'

class sm:
    """SIDE MENU"""
    checkOutLbl = '//h2[text()="Checkout"]'
    checkOutDescLbl = '//p[text()="Complete the form to proceed with your Checkout."]'
    
class co:
    """CHECKOUT"""
    deliveryAddressLbl = '//p[text()="Delivery Address"]'
    selectYourAddressLbl= '//p[text()=" Select from your address list or add a new one. "]'
    userIconImg = '//mat-icon[text()="person"]'
    userNameLbl = f'{userIconImg}/../p[@class="name"]'
    defaultLbl = f'{userIconImg}/../span[text()="Default"]'
    editBtn = '//mat-icon[text()="edit"]'
    phoneIconImg = '//mat-icon[text()="local_phone"]'
    phoneLbl = f'{phoneIconImg}/../p[@class="number"]'
    addressIconImg = '//mat-icon[text()="place"]'
    addressLbl = f'{addressIconImg}/../p[@class="address"]'
    newAddressBtn = '//p[text()="New Address"]'
    changeAddressBtn = '//p[text()="Change Address"]'
    cartSummaryLbl = '//h2[text()="Cart Summary"]'
    itemqQuantityLbl = '//p[@class="quantity"]'
    itemBrandLbl = '//span[@class="brand"]'
    itemnameLbl = '//span[@class="name"]'
    itemColorLbl = '//p[@class="variant"]'
    itemPriceLbl = '//p[@class="default-price"]'
    itemDisPriceLbl = '//p[@class="discounted-price"]'
    discountedAmountLbl = '//p[contains(text(),"Discounted Amount")]'
    shippingAmountLbl = '//p[contains(text(),"Shipping Amount")]'
    creditUsedTotalLbl = '//p[contains(text(),"Credit Used Total")]'
    collectibleTotalLbl = '//p[contains(text(),"Collectible Total")]'
    
    expressDeliveryLbl = '//b[text()="Express Delivery"]'
    expressDeliveryIconImg = '//img[@src="assets/images/i-icon.svg"]'

class pm:
    """PAYMENT"""
    paymentLbl = '//p[text()="Payment"]'
    selectPaymentLbl = '//p[contains(text(),"Select a payment option.")]'
    creditCardLbl = '//div[contains(text(),"Credit/Debit Card")]'
    creditCardRdb = f'{creditCardLbl}/..//input[@name="paymentMethod"]'
    gCashLbl = '//div[contains(text(),"GCash")]'
    gCashRdb = f'{gCashLbl}/..//input[@name="paymentMethod"]'
    grabPayLbl = '//div[contains(text(),"GrabPay")]'
    grabPayRdb = f'{grabPayLbl}/..//input[@name="paymentMethod"]'
    mayaLbl = '//div[contains(text(),"Maya")]'
    mayaRdb = f'{mayaLbl}/..//input[@name="paymentMethod"]'
    cashOnDeliveryLbl = '//div[contains(text(),"Cash On Delivery")]'
    cashOnDeliveryRdb = f'{cashOnDeliveryLbl}/..//input[@name="paymentMethod"]'
    pickATreatLbl = '//p[contains(text(),"Pick a Treat")]'
    minSpendOfLbl = '//p[contains(text(),"Min spend of")]'
    allPickTreatItems = '//div[@class="pick-a-treat-items"]//p[@class="name"]'
    beansPromoLbl = '//p[text()="Beans & Promo"]'
    beansPromoDescLbl = '//p[contains(text(),"Use your beans or enter a promo")]'
    useBeansLbl = '//span[contains(text(),"Use Bean Rewards")]'
    useBeansRdb = f'{useBeansLbl}/..//input[@type="radio"]'
    totalBeanLbl = '//span[@class="total-beans"]'
    toalBeanImg = f'{totalBeanLbl}/..//img[@src="assets/images/discounts/beans.svg"]'
    totalBeanRewardToUseLbl = f'{useBeansLbl}/../div/span[1]'
    enterPromoCodeLbl = '//span[contains(text(),"Enter Promo Code")]'
    enterPromoCodeRdb = f'{enterPromoCodeLbl}/..//input[@type="radio"]'
    availablePromoCodeLbl = '//span[contains(text(),"Available")]'
    arrowForwardIconBtn = f'{availablePromoCodeLbl}/..//mat-icon'
    orderDetailsLbl = '//p[text()="Order Details"]'
    subTotalLbl = '//p[text()="Subtotal"]'
    subTotalAmountLbl = f'{subTotalLbl}/../p[@class="value"]'
    markdownLbl = '//p[text()="Markdown"]'
    markdownTotalAmountLbl = f'{markdownLbl}/../p[@class="value"]'
    giftWrapLbl = '//p[text()="Gift Wrap"]'
    giftWrapAmountLbl = f'{giftWrapLbl}/../p[@class="value"]'
    shippingLbl = '//p[text()="Shipping"]'
    shippingAmountLbl = f'{shippingLbl}/../p[@class="value ng-star-inserted"]'
    totalLbl = '//p[text()="Total"]'
    totalAmountLbl = f'{totalLbl}/../p[@class="value"]'
    xenditTestAmountLbl = '//span[text()="Xendit Test Amount:"]'
    xenditTestAmountTxt = f'{xenditTestAmountLbl}/..//input'
    placeOrderBtn = '//button[contains(text(),"Place Order")]'
    
    promoCodeLbl = '//p[@class="code"]'
    promoCodeDoesNotExistMsg = '//span[text()="Error: Promo code does not exist."]'
    promoAmountLbl = '//p[@class="amount"]'
    promoDescLbl = '//div[contains(text(),"Your bean rewards will be manually credited to your account within 30 days after all items in your order are delivered.")]'
    cardNumberLbl = '//span[@class="fullname"]'
    
class cc:
    """CREDIT CARD"""
    xbtn = xbtn
    payWithCreditCardLbl = '//H3[text()="Pay With Credit Card"]'
    contactPersonLbl = '//legend[text()="Contact Person"]'
    paySecurelyLbl = '//p[text()="Pay securely using your Visa or Mastercard"]'
    cardHoldersNameLbl = '//label[text()="Cardholder\'s Name"]'
    cardHoldersNameTxt = f'{cardHoldersNameLbl}/..//input'
    cardNumberLbl = '//label[text()="Card Number"]'
    cardNumberTxt = f'{cardNumberLbl}/..//input'
    validThruLbl = '//label[text()="Valid Thru"]'
    validThruTxt = f'{validThruLbl}/..//input'
    cvvCnnLbl = '//label[text()="CVV/CVN"]'
    cvvCnnTxt = f'{cvvCnnLbl}/..//input'
    billingAddressLbl = '//legend[text()="Billing Address"]'
    sameAsDeliveryAddLbl = '//p[text()=" Same as my delivery address: "]'
    billingAddressTgl = '//label[@class="switch"]'
    contryLbl = '//label[text()="Country"]'
    contryDdb = '//mat-select[@formcontrolname="country"]'
    stateProvinceRegionLbl = '//label[text()="State/Province/Region"]'
    stateProvinceRegionTxt = f'{stateProvinceRegionLbl}/..//input'
    cityDistrictLbl = '//label[text()="City/District"]'
    cityDistrictTxt = f'{cityDistrictLbl}/..//input'
    zipCodeLbl = '//label[text()="Zip Code"]'
    zipCodeTxt = f'{zipCodeLbl}/..//input'
    addressLine1Lbl = '//label[text()="Address Line 1"]'
    addressLine1Txt = f'{addressLine1Lbl}/..//input'
    addressLine2OptionalLbl = '//label[text()="Address Line 2 - Optional"]'
    addressLine2OptionalTxt = f'{addressLine2OptionalLbl}/..//input'
    mobileNumberLbl = '//label[text()="Mobile Number"]'
    mobileNumberTxt = f'{mobileNumberLbl}/..//input'
    cancelBtn = '//button[text()="Cancel"]'
    confirmBtn = '//button[text()=" Confirm "]'
    
class pc:
    """ENTER PROMO CODE"""
    enterPromocodeLbl = '//p[text()="Enter Promo Code"]'
    xbtn = xbtn
    enterPromoCodeTxt = '//input[@placeholder="Enter Promo Code"]'
    applyBtn = '//button[contains(text(),"Apply")]'
    
class ty:
    """THANK YOU"""
    orderSuccessImg = '//img[@src="assets/images/thank-you/thank-you-check.svg"]'
    thankYouLbl = '//h1[normalize-space(text())="Thank you for"][text()=" choosing edamama "]'
    thankYouDescLbl = '//p[normalize-space(text())="Your order has been placed and will be processed"][text()=" right away! Click "][text()=" for order updates. "]'
    trackerOrderLbl = '//b[text()="Track Order"]'
    orderIDLbl = '//p[text()="Order ID"]'
    ordelIDCodeLbl = f'{orderIDLbl}/..//span[@class="col order-number"]'
    backToShoppingBtn = '//a[normalize-space(text())="Back to Shopping"]'
    trackOrderBtn = '//a[normalize-space(text())="Track Order"]'